services:
  bot:
    build: .
    environment:
      NODE_ENV: production
    restart: always
    env_file: .env.docker-compose
    depends_on:
      - db
      - minio
    links:
      - db
      - minio

  db:
    image: postgres:14-alpine
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: 21oueasdkjbkaek

  minio:
    image: quay.io/minio/minio
    command:
      - server
      - --address
      - 0.0.0.0:9000
      - /data
    volumes:
      - "/data"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY