services:
  bot:
    build: .
    environment:
      NODE_ENV: production
    env_file:
      - .env.docker-compose
    depends_on:
      - db
      - minio
    links:
      - db
      - minio

  db:
    image: postgres:14-alpine
    volumes:
      - "/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: 21oueasdkjbkaek

  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z.hotfix.c1d7c4c9d
    command:
      - server
      - /data
    volumes:
      - "/data"
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY